jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app customtkinter
      - name: Build app
        run: |
          python3 setup.py py2app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/*.app
